In [136]:

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from skopt import gp_minimize
from skopt.space import Integer
from numpy import mean
from skopt.utils import use_named_args
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score, explained_variance_score, median_absolute_error
import numpy as np
import pandas as pd
#
from sklearn.tree import DecisionTreeRegressor



In [ ]:
dataset = pd.read_csv('./Dataset/dataset.csv')
# 
features = ["Freq"]
targets = ["W", "L", "Lf"]
x = dataset[features]
y = dataset[targets]

In [ ]:
# Split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=1)

# Scaling
scaler = StandardScaler()
x_train_scaled = scaler.fit_transform(x_train)
x_test_scaled = scaler.transform(x_test)

In [139]:
search_space = [Integer(1, 999999999999999, name='max_depth'), Integer(2, 999999999999999, name='min_samples_split')]

In [ ]:
@use_named_args(search_space)
def evaluate_model(**params):
    model = DecisionTreeRegressor(max_depth=params['max_depth'], min_samples_split=params['min_samples_split'])
    model.fit(x_train_scaled, y_train)
    y_pred = model.predict(x_test_scaled)
    error = mean((y_test - y_pred) ** 2)  # MSE
    return error

In [141]:
result = gp_minimize(evaluate_model, search_space)

C:\Users\sachxn\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\skopt\space\transformers.py:267: RuntimeWarning: invalid value encountered in cast
  return np.round(X_orig).astype(int)
C:\Users\sachxn\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\skopt\space\transformers.py:267: RuntimeWarning: invalid value encountered in cast
  return np.round(X_orig).astype(int)
C:\Users\sachxn\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\skopt\space\transformers.py:267: RuntimeWarning: invalid value encountered in cast
  return np.round(X_orig).astype(int)
C:\Users\sachxn\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\skopt\space\transformers.py:267: RuntimeWarning: invalid value encountered in cast
  

In [142]:
best_max_depth = result.x[0]
best_min_samples_split = result.x[1]
best_model = DecisionTreeRegressor(max_depth=best_max_depth, min_samples_split=best_min_samples_split)
best_model.fit(x_train_scaled, y_train)

DecisionTreeRegressor(max_depth=2100629544)

In [ ]:
#
new_dataset = pd.read_csv('./Dataset/paraS.csv')  # 
new_data = new_dataset["Freq"].values.reshape(-1, 1)  # 

# Scaling 
new_data_scaled = scaler.transform(new_data)

# 
y_pred = best_model.predict(x_test_scaled)
y_pred.size
# df_y_pred = pd.DataFrame(y_pred)
# df_y_pred.to_csv('y_pred.csv',index=False)

C:\Users\sachxn\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


582

In [ ]:
print('Best Accuracy: %.3f' % (1.0 - result.fun))
print('Best Parameters: max_depth=%d, min_samples_split=%d' % (result.x[0], result.x[1]))

# 

print("Predictions:", y_pred)
y_pred.size
# df_y_pred = pd.DataFrame(y_pred)
# df_y_pred.to_csv('y_pred.csv',index=False)

Best Accuracy: 0.994
Best Parameters: max_depth=2100629544, min_samples_split=2
Predictions: [[ 25.57  19.58  11.52]
 [ 49.26  38.29  22.19]
 [109.6   85.72  49.4 ]
 [ 38.36  29.7   17.28]
 [ 25.47  19.5   11.47]
 [ 17.18  12.9    7.74]
 [ 26.86  20.61  12.1 ]
 [ 44.85  34.82  20.21]
 [ 29.41  22.62  13.25]
 [ 43.23  33.54  19.48]
 [ 38.79  30.03  17.47]
 [100.7   78.69  45.36]
 [ 35.5   27.44  15.99]
 [ 39.19  30.35  17.65]
 [ 24.72  18.91  11.14]
 [ 95.22  74.4   42.9 ]
 [ 27.12  20.81  12.22]
 [ 37.76  29.22  17.01]
 [ 28.03  21.53  12.63]
 [ 25.52  19.54  11.5 ]
 [ 49.85  38.75  22.46]
 [ 35.36  27.33  15.93]
 [ 17.36  13.05   7.82]
 [ 17.13  12.86   7.72]
 [ 51.48  40.04  23.19]
 [ 16.6   12.44   7.48]
 [ 34.01  26.27  15.32]
 [107.6   84.09  48.46]
 [103.4   80.84  46.59]
 [ 18.01  13.57   8.11]
 [ 34.4   26.57  15.5 ]
 [ 38.46  29.78  17.33]
 [ 93.28  72.87  42.02]
 [ 44.76  34.75  20.16]
 [ 51.19  39.81  23.06]
 [ 15.89  11.87   7.16]
 [111.2   86.97  50.12]
 [104.6   81.17  47

582

In [ ]:
# FreqInput = float(input('Nhập vào tần số muốn dự đoán: '))
FreqInput = 1.2
# 
new_data = [[FreqInput]]

# Scaling 
new_data_scaled = scaler.transform(new_data)

# 
y_pred = best_model.predict(new_data_scaled)

# 
print('Giá trị nhập vào là: ', FreqInput)
print('Giá trị dự đoán:', y_pred)

In [ ]:
def regression_report(y_true, y_pred):
    mae = mean_absolute_error(y_true, y_pred)
    mse = mean_squared_error(y_true, y_pred)
    rmse = np.sqrt(mse)
    r2 = r2_score(y_true, y_pred)
    explained_variance = explained_variance_score(y_true, y_pred)
    median_ae = median_absolute_error(y_true, y_pred)

    # Mean Bias Deviation (MBD)
    mbd = np.mean(y_pred - y_true)

    # Mean Absolute Percentage Error (MAPE)
    mape = np.mean(np.abs((y_true - y_pred) / y_true)) * 100

    # Symmetric Mean Absolute Percentage Error (sMAPE)
    smape = np.mean(2 * np.abs(y_pred - y_true) / (np.abs(y_true) + np.abs(y_pred))) * 100

    report = pd.DataFrame({
        'Metric': [
            'Mean Absolute Error (MAE)',
            'Mean Squared Error (MSE)',
            'Root Mean Squared Error (RMSE)',
            'R² Score',
            'Explained Variance Score',
            'Median Absolute Error',
            'Mean Bias Deviation (MBD)',
            'Mean Absolute Percentage Error (MAPE)',
            'Symmetric Mean Absolute Percentage Error (sMAPE)'
        ],
        'Gausians': [mae, mse, rmse, r2, explained_variance, median_ae, mbd, mape, smape]
    })

    return report

report = regression_report(y_test, y_pred)
print(report)

                                             Metric  Gausians
0                         Mean Absolute Error (MAE)  0.042534
1                          Mean Squared Error (MSE)  0.006382
2                    Root Mean Squared Error (RMSE)  0.079889
3                                          R² Score  0.999985
4                          Explained Variance Score  0.999985
5                             Median Absolute Error  0.020000
6                         Mean Bias Deviation (MBD)  0.010507
7             Mean Absolute Percentage Error (MAPE)  0.103837
8  Symmetric Mean Absolute Percentage Error (sMAPE)  0.103824
