In [12]:

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from skopt import gp_minimize
from skopt.space import Integer
from numpy import mean
from skopt.utils import use_named_args

#
from sklearn.linear_model import Lasso
import numpy as np
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score, explained_variance_score, median_absolute_error

In [ ]:
#dataset = pd.read_csv('D:/Code/Python/NCKH/A1/c.csv')
dataset = pd.read_csv('./Dataset/para.csv')
# 
features = ["Freq"]
targets = ["W", "L", "Lf"]
x = dataset[features]
y = dataset[targets]

In [14]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=1)

# Scaling
scaler = StandardScaler()
x_train_scaled = scaler.fit_transform(x_train)
x_test_scaled = scaler.transform(x_test)

In [15]:
search_space = [Integer(1, 10, name='max_iter'), Integer(2, 10, name='alpha')]

In [ ]:
@use_named_args(search_space)
def evaluate_model(**params):
    model = Lasso(max_iter=params['max_iter'], alpha=params['alpha'])
    model.fit(x_train_scaled, y_train)
    y_pred = model.predict(x_test_scaled)
    error = mean((y_test - y_pred) ** 2)  # MSE
    return error

In [17]:
result = gp_minimize(evaluate_model, search_space)

C:\Users\sachxn\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\skopt\optimizer\optimizer.py:517: UserWarning: The objective has been evaluated at point [1, 2] before, using random point [5, 6]
  warnings.warn(
C:\Users\sachxn\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\skopt\optimizer\optimizer.py:517: UserWarning: The objective has been evaluated at point [1, 2] before, using random point [7, 6]
  warnings.warn(
C:\Users\sachxn\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\skopt\optimizer\optimizer.py:517: UserWarning: The objective has been evaluated at point [1, 2] before, using random point [4, 2]
  warnings.warn(
C:\Users\sachxn\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\skopt\o

In [18]:
best_max_iter = result.x[0]
best_alpha = result.x[1]
best_model = Lasso(max_iter=best_max_iter, alpha=best_alpha)
best_model.fit(x_train_scaled, y_train)

Lasso(alpha=2, max_iter=6)

In [ ]:
new_dataset = pd.read_csv('./Dataset/para.csv')  # 
new_data = new_dataset["Freq"].values.reshape(-1, 1)  # 

# Scaling 
new_data_scaled = scaler.transform(new_data)

# 
y_pred = best_model.predict(x_test_scaled)

C:\Users\sachxn\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


In [ ]:
print('Best Accuracy: %.3f' % (1.0 - result.fun))
print('Best Parameters: max_iter=%d, alpha=%.2f' % (result.x[0], result.x[1]))

# 

print("Predictions:", y_pred)

Best Accuracy: -143.172
Best Parameters: max_iter=6, alpha=2.00
Predictions: [[31.4869638  24.41569317 14.66067084]
 [53.38523357 41.14305046 23.1028348 ]
 [66.478255   51.14437248 28.15042235]
 [46.72387179 36.05465856 20.53476395]
 [31.30830659 24.27922288 14.59179537]
 [ 9.21861838  7.40564743  6.07583626]
 [33.68189527 26.09232805 15.5068551 ]
 [51.06268981 39.36893681 22.20745378]
 [37.48474165 28.99719546 16.97291854]
 [50.14388128 38.66708965 21.85323711]
 [47.00461884 36.26911186 20.64299682]
 [65.45735665 50.3645423  27.75684827]
 [44.27371573 34.18306613 19.59018616]
 [47.36193326 36.54205242 20.78074774]
 [29.93009381 23.22645215 14.06047037]
 [64.79377271 49.85765269 27.50102512]
 [34.09025461 26.40426012 15.66428473]
 [46.23894507 35.68423922 20.34781626]
 [35.49398985 27.47652661 16.20544909]
 [31.41039642 24.3572059  14.63115278]
 [53.66598062 41.35750376 23.21106767]
 [44.09505852 34.04659585 19.5213107 ]
 [ 9.920486    7.94178068  6.34641844]
 [ 9.02719994  7.25942927 

In [ ]:
FreqInput = float(input('Nhập vào tần số muốn dự đoán: '))

# 
new_data = [[FreqInput]]

# Scaling 
new_data_scaled = scaler.transform(new_data)

# 
y_pred = best_model.predict(new_data_scaled)

# 
print('Giá trị nhập vào là: ', FreqInput)
print('Giá trị dự đoán:', y_pred)

In [ ]:
def regression_report(y_true, y_pred):
    mae = mean_absolute_error(y_true, y_pred)
    mse = mean_squared_error(y_true, y_pred)
    rmse = np.sqrt(mse)
    r2 = r2_score(y_true, y_pred)
    explained_variance = explained_variance_score(y_true, y_pred)
    median_ae = median_absolute_error(y_true, y_pred)

    # Mean Bias Deviation (MBD)
    mbd = np.mean(y_pred - y_true)

    # Mean Absolute Percentage Error (MAPE)
    mape = np.mean(np.abs((y_true - y_pred) / y_true)) * 100

    # Symmetric Mean Absolute Percentage Error (sMAPE)
    smape = np.mean(2 * np.abs(y_pred - y_true) / (np.abs(y_true) + np.abs(y_pred))) * 100

    report = pd.DataFrame({
        'Metric': [
            'Mean Absolute Error (MAE)',
            'Mean Squared Error (MSE)',
            'Root Mean Squared Error (RMSE)',
            'R² Score',
            'Explained Variance Score',
            'Median Absolute Error',
            'Mean Bias Deviation (MBD)',
            'Mean Absolute Percentage Error (MAPE)',
            'Symmetric Mean Absolute Percentage Error (sMAPE)'
        ],
        'Gausians': [mae, mse, rmse, r2, explained_variance, median_ae, mbd, mape, smape]
    })

    return report

report = regression_report(y_test, y_pred)
print(report)

                                             Metric    Gausians
0                         Mean Absolute Error (MAE)    8.083890
1                          Mean Squared Error (MSE)  144.172150
2                    Root Mean Squared Error (RMSE)   12.007171
3                                          R² Score    0.640779
4                          Explained Variance Score    0.644505
5                             Median Absolute Error    5.615071
6                         Mean Bias Deviation (MBD)   -1.172266
7             Mean Absolute Percentage Error (MAPE)   26.181020
8  Symmetric Mean Absolute Percentage Error (sMAPE)   28.227217
